apiVersion: v1
kind: Service
metadata:
  name: devkraft
  labels:
    app: devkraft
spec:
  type: NodePort
  ports:
  - port: 1213
    targetPort: 1213
    nodePort: 30008
  selector:
    app: devkraft
